server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

        - id: product_service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/products/**
            - Path=/api/v1/categories/**
          filters:
            - StripPrefix=2  
