server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - name: JwtAuthFilter

      routes:
        - id: user_service
          uri: lb://user-service
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2

        - id: product_service
          uri: lb://product-service  
          predicates:
            - Path=${app.api-prefix}/products/**, ${app.api-prefix}/categories/**
          filters:
            - StripPrefix=2

jwt:
  secret: "secret"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  # URL của Eureka Server
