server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - name: JwtAuthFilter

      routes:
        - id: user_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/auth/**
          filters:
            - StripPrefix=2
        - id: product_service
          uri: http://localhost:8080
          predicates:
            - Path=${app.api-prefix}/products/**, ${app.api-prefix}/categories/**
          filters:
            - StripPrefix=2

jwt:
  secret: your_secret_key_here
